#!/bin/bash

##############################
######## CONFIG BEGIN ########
##############################

# Project Name
PROJ="default"

# Pick a compiler (default: clang)
CC="default"

# Pick a linker (ld | lld)
LD="-fuse-ld=default"

# List source files here
SRC="default"

# Header directory
HEADERS="headers/*.h"

# Pick a C standard (c89 | c99 | c11 | c17 | c18 | c2x)
CSTD="-std=c18"

# Default warning flags
STDCFLAGS="-Wall -Wextra -pedantic"

# Optimization (-Oz | -Os | -O0 | -O1 | -O2 | -O3 | -Ofast)
OPTFLAGS="-O3"

# Debug flags
DEBUG="-g3"

# Extra warnings
EXTRAFLAGS="-Wshadow -Wdouble-promotion -Wconversion -Wpadded"

# Linker flags. Popular options (-lm | -lncurses)
LDFLAGS=""

# static analyzer to use (clang-analyzer | infer | none)
ANALYZER="clang-analyzer"


############################
######## CONFIG END ########
############################


# global variables
INFER="./tools/infer-linux64-v1.1.0/bin/infer"

red='\e[31m'
green='\e[32m'
blue='\e[34m'
bold='\e[1m'
clear='\e[0m'

envClang="
{ pkgs ? import <nixpkgs> {} }:\n
pkgs.mkShell {\n
  buildInputs = [\n
    pkgs.clangStdenv\n
    pkgs.clang_13\n
    pkgs.clang-tools\n
    pkgs.clang-analyzer\n
    pkgs.lldb\n
    pkgs.llvmPackages_13.bintools\n
# pkgs.lld_13\n
    pkgs.man\n
    pkgs.man-pages\n
    pkgs.bashInteractive\n
  ];\n
}"

envGCC="
{ pkgs ? import <nixpkgs> {} }:\n
pkgs.mkShell {\n
  buildInputs = [\n
    pkgs.gccStdenv\n
    pkgs.gcc\n
    pkgs.clang-tools\n
    pkgs.gdb\n
    pkgs.man\n
    pkgs.man-pages\n
    pkgs.bashInteractive\n
  ];\n
}"

function texo_help() {
    clear
    #TODO: beautify
    echo -e $blue"

████████╗███████╗██╗  ██╗ ██████╗
╚══██╔══╝██╔════╝╚██╗██╔╝██╔═══██╗
   ██║   █████╗   ╚███╔╝ ██║   ██║
   ██║   ██╔══╝   ██╔██╗ ██║   ██║
   ██║   ███████╗██╔╝ ██╗╚██████╔╝
   ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝
                                  "$clear
    echo -e $bold"Usage:$clear texo [command]\n"
    echo -e $bold"  Available commands:\n"$clear
    echo -e "  init | i\t\t\tinit project"
    echo -e "  shell | sh\t\t\tload shell env"
    echo -e "  fetch | f | update | u\tfetch latest changes"
    echo -e "  build | c | com | compile\tbuild project"
    echo -e "  clean\t\t\t\tcleanup"
    echo -e "  tidy | t\\t\t\ttrun clang-tidy"
    echo -e "  analyze | lint | a | l\trun static analyzer"
}

function texo_config_check(){
    local def="default"
    if [[ $PROJ = $def || $CC = $def || $LD = "-fuse-ld=default" || $SRC = $def ]]; then
        echo -ne $red"ERROR: please visit the config section before invoking texo\n"$clear
        exit
    fi
}

function texo_init(){
    echo -ne $green"WORKING: creating folders\n"$clear
    mkdir -p static-analysis tools headers
    #TODO: make this user configurable
    echo -ne $green"WORKING: write shell.nix\n"$clear
    if [[ $CC = 'gcc' ]]; then
        echo -e $envGCC > shell.nix
    elif [[ $CC = 'clang' ]]; then
        echo -e $envClang > shell.nix
    else
        echo -ne $red"ERROR: no compiler configured\n"$clear
    fi

    local analyzer_infer="infer"
    local analyzer_clang="clang-analyzer"
    if [[ $ANALYZER = $analyzer_infer ]]; then
        echo -ne $green"WORKING: downloading and installing infer\n"$clear
        curl -o tools/infer-1.1.0.tar.xz -L https://github.com/facebook/infer/releases/download/v1.1.0/infer-linux64-v1.1.0.tar.xz
        tar -xf tools/infer-1.1.0.tar.xz -C tools/
        rm tools/infer-1.1.0.tar.xz
    elif [[ $ANALYZER = $analyzer_clang ]]; then
        echo -ne $blue"INFO: using clang static analyzer\n"$clear
    else
        echo -ne $red"ERROR: no static analyzer configured\n"$clear
    fi
}

function texo_shell(){
    #TODO: maybe use --pure
    echo -ne $green"WORKING: entering nix-shell\n"$clear
    nix-shell shell.nix
}

function texo_fetch(){
    set -xe
    git reset --hard
    git pull --rebase
}

function texo_compile(){
    set -xe
    $CC $LD $CSTD $STDFLAGS $OPTFLAGS $DEBUG $EXTRAFLAGS $LDFLAGS -o $PROJ $SRC
}

function texo_clean(){
    set -xe
    rm -rfv *.o *.out $PROJ *~ infer-out
}

function texo_tidy(){
    set -xe
    clang-tidy $SRC $HEADERS
}

function texo_analyze(){
    local analyzer_infer="infer"
    local analyzer_clang="clang-analyzer"
    set -xe
    if [[ $ANALYZER = $analyzer_infer ]]; then
        $INFER run --reactive --continue -- $CC $LDFLAGS $LD $SRC -o static-analysis/inf.out
    elif [[ $ANALYZER = $analyzer_clang ]]; then
        #TODO: check clang-analyzer if this really works
        scan-build -k -v --force-analyze-debug-code -o static-analysis/ $CC $SRC
    elif [[ $ANALYZER = "none" ]]; then
        echo -ne $red"ERROR: no static analyzer configured\n"$clear
    else
        echo -ne $red"ERROR: not a valid option: "$clear
        echo -e $ANALYZER
        echo -e "\n"
    fi
}

case $1 in
    init | i)
        texo_config_check
        texo_init
        ;;
    shell | sh)
        texo_config_check
        texo_shell
        ;;
    fetch | f | update | u)
        texo_config_check
        texo_fetch
        ;;
    com | compile | c | build)
        texo_config_check
        texo_compile
        ;;
    clean)
        texo_config_check
        texo_clean
        ;;
    tidy | t)
        texo_config_check
        texo_tidy
        ;;
    analyze | lint | a | l)
        texo_config_check
        texo_analyze
        ;;
    *)
        clear
        texo_help
        ;;
esac
